// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RollCallApp.Models;

namespace RollCallApp.Migrations
{
    [DbContext(typeof(RollCallContext))]
    partial class RollCallContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RollCallApp.Models.AttendanceRollCall", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("ID")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("CheckAttendance")
                        .HasColumnName("checkAttendance")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("DateCheck")
                        .HasColumnName("dateCheck")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("RegisterId")
                        .HasColumnName("registerID")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("ATTENDANCE_ROLL_CALL");
                });

            modelBuilder.Entity("RollCallApp.Models.Contact", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("ID")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("Content")
                        .HasColumnName("content")
                        .HasMaxLength(255);

                    b.Property<string>("StudentId")
                        .HasColumnName("StudentID")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("SubjectId")
                        .HasColumnName("SubjectID")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Title")
                        .HasColumnName("title")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("CONTACT");
                });

            modelBuilder.Entity("RollCallApp.Models.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("ID")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Content")
                        .HasColumnName("content")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("DateCreate")
                        .HasColumnName("dateCreate")
                        .HasColumnType("datetime");

                    b.Property<string>("SubjectId")
                        .HasColumnName("subjectID")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("TeacherId")
                        .HasColumnName("teacherID")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Title")
                        .HasColumnName("title")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("NOTIFICATION");
                });

            modelBuilder.Entity("RollCallApp.Models.ProfileStudent", b =>
                {
                    b.Property<string>("ProfileId")
                        .HasColumnName("profileID")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Address")
                        .HasColumnName("address")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("Avatar");

                    b.Property<string>("ClassId")
                        .HasColumnName("classID")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("DepartmentId")
                        .HasColumnName("departmentID")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("FullName")
                        .HasColumnName("fullName")
                        .HasMaxLength(255);

                    b.Property<string>("PhoneNumber")
                        .HasColumnName("phoneNumber")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("ProfileId");

                    b.ToTable("PROFILE_STUDENT");
                });

            modelBuilder.Entity("RollCallApp.Models.ProfileTeacher", b =>
                {
                    b.Property<string>("ProfileId")
                        .HasColumnName("profileID")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Address")
                        .HasColumnName("address")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("Avatar");

                    b.Property<string>("DepartmentId")
                        .HasColumnName("departmentID")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("FullName")
                        .HasColumnName("fullName")
                        .HasMaxLength(255);

                    b.Property<string>("PhoneNumber")
                        .HasColumnName("phoneNumber")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Specialize")
                        .HasColumnName("specialize")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.HasKey("ProfileId");

                    b.ToTable("PROFILE_TEACHER");
                });

            modelBuilder.Entity("RollCallApp.Models.RegisterSubject", b =>
                {
                    b.Property<string>("RegisterId")
                        .HasColumnName("registerID")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("DateEnd")
                        .HasColumnName("dateEnd")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("DateStart")
                        .HasColumnName("dateStart")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("StudentId")
                        .HasColumnName("studentID")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("SubjectId")
                        .HasColumnName("subjectID")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("TeacherId")
                        .HasColumnName("teacherID")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("RegisterId");

                    b.ToTable("REGISTER_SUBJECT");
                });

            modelBuilder.Entity("RollCallApp.Models.Student", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnName("studentID")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("FaceId")
                        .HasColumnName("faceID")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("Password");

                    b.Property<string>("PersonId")
                        .HasColumnName("personID")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("ProfileId")
                        .HasColumnName("profileID")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("StudentId");

                    b.ToTable("STUDENT");
                });

            modelBuilder.Entity("RollCallApp.Models.Subject", b =>
                {
                    b.Property<string>("SubjectId")
                        .HasColumnName("subjectID")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("SubjectName")
                        .HasColumnName("subjectName")
                        .HasMaxLength(150);

                    b.HasKey("SubjectId");

                    b.ToTable("SUBJECT");
                });

            modelBuilder.Entity("RollCallApp.Models.Teacher", b =>
                {
                    b.Property<string>("TeacherId")
                        .HasColumnName("teacherID")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Password");

                    b.Property<string>("ProfileId")
                        .HasColumnName("profileID")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("TeacherId");

                    b.ToTable("TEACHER");
                });
#pragma warning restore 612, 618
        }
    }
}
